Repository Block-Guard/BlockGuard-Server, pull requests merged in 2025-08, with the labels that each got.

#44 [Feat] 뉴스 API
  build.gradle
  src/main/java/com/blockguard/server/domain/admin/api/AdminApi.java
  src/main/java/com/blockguard/server/domain/analysis/application/FraudAnalysisService.java
  src/main/java/com/blockguard/server/domain/news/api/NewsApi.java
  src/main/java/com/blockguard/server/domain/news/application/NewsService.java
  src/main/java/com/blockguard/server/domain/news/dao/NewsRepository.java
  src/main/java/com/blockguard/server/domain/news/domain/NewsArticle.java
  src/main/java/com/blockguard/server/domain/news/domain/enums/Category.java
  src/main/java/com/blockguard/server/domain/news/dto/response/NewsArticleResponse.java
  src/main/java/com/blockguard/server/domain/news/dto/response/NewsPageResponse.java
  src/main/java/com/blockguard/server/domain/news/dto/response/PageableInfo.java
  src/main/java/com/blockguard/server/domain/news/scheduler/NewsSaveScheduler.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/com/blockguard/server/infra/crawler/DaumNewsCrawler.java
  src/main/java/com/blockguard/server/infra/naver/ocr/ByteArrayResourceWithFilename.java
  src/main/java/com/blockguard/server/infra/naver/ocr/NaverOcrClient.java
  src/test/java/com/blockguard/server/infra/crawler/DaumNewsCrawlerTest.java
Labels: 🐼 채유, 🚀 Feature

#45 [Refactor] 관리자용 API 추가
  src/main/java/com/blockguard/server/domain/admin/api/AdminApi.java
  src/main/java/com/blockguard/server/domain/auth/application/AuthService.java
  src/main/java/com/blockguard/server/domain/auth/infra/JwtTokenGenerator.java
  src/main/java/com/blockguard/server/domain/auth/infra/JwtTokenProvider.java
  src/main/java/com/blockguard/server/domain/auth/interceptor/AdminCheckInterceptor.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/global/config/WebMvcConfig.java
Labels: ➕ Refactor, 🐼 채유

#46 [Feat] 전화번호 사기분석 API
  src/main/java/com/blockguard/server/domain/fraud/api/FraudApi.java
  src/main/java/com/blockguard/server/domain/fraud/application/FraudService.java
  src/main/java/com/blockguard/server/domain/fraud/dto/request/FraudPhoneNumberRequest.java
  src/main/java/com/blockguard/server/domain/fraud/dto/response/FraudRiskLevelResponse.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/com/blockguard/server/infra/number/CheckFraudNumberResponse.java
  src/main/java/com/blockguard/server/infra/number/FraudNumberClient.java
Labels: 🐶 연주, 🚀 Feature

#55 [Fix] 프로필 이미지 조회 오류 수정
  src/main/java/com/blockguard/server/domain/user/dto/response/MyPageResponse.java
Labels: 🐞 BugFix, 🐶 연주

#56 [Refactor] deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, ➕ Refactor, 🐼 채유

#61 [Fix] deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🐼 채유

#53 [Feat] 사기분석 api : url/전화번호 추가점수 로직 구현
  src/main/java/com/blockguard/server/domain/analysis/api/FraudAnalysisApi.java
  src/main/java/com/blockguard/server/domain/analysis/application/FraudAnalysisService.java
  src/main/java/com/blockguard/server/domain/analysis/dao/FraudAnalysisRecordRepository.java
  src/main/java/com/blockguard/server/domain/analysis/domain/FraudAnalysisRecord.java
  src/main/java/com/blockguard/server/domain/analysis/domain/enums/FraudType.java
  src/main/java/com/blockguard/server/domain/analysis/dto/request/FraudAnalysisRequest.java
  src/main/java/com/blockguard/server/domain/analysis/dto/response/FraudAnalysisRecordResponse.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/WebMvcConfig.java
  src/main/java/com/blockguard/server/global/config/resolver/OptionalUser.java
  src/main/java/com/blockguard/server/global/config/resolver/OptionalUserArgumentResolver.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
Labels: 🐶 연주, 🚀 Feature

#66 [Feat] 사기분석설문 로직 변경 & 기타 키워드 제외 & 진행중인 긴급 대응 조회 API 응답변경
  src/main/java/com/blockguard/server/domain/analysis/application/FraudAnalysisService.java
  src/main/java/com/blockguard/server/domain/report/application/ReportRecordService.java
  src/main/java/com/blockguard/server/domain/report/dto/response/CurrentReportRecordResponse.java
Labels: 🐶 연주, 🚀 Feature

#71 [Fix] 회원가입오류 메세지 수정
  src/main/java/com/blockguard/server/domain/auth/application/AuthService.java
  src/main/java/com/blockguard/server/domain/user/dao/UserRepository.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
Labels: 🐞 BugFix, ➕ Refactor, 🐼 채유

#73 [Refactor] 뉴스 저장 기간 수정
  src/main/java/com/blockguard/server/ServerApplication.java
  src/main/java/com/blockguard/server/infra/crawler/DaumNewsCrawler.java
Labels: ➕ Refactor, 🐼 채유

#78 [Docs] README.md 작성
  README.md
  img.png
  img_1.png
  img_2.png
  img_3.png
  img_4.png
Labels: 📄 Documentation, 🐶 연주, 🐼 채유

#84 [Refactor] 핵심 키워드 뉴스 크롤링
  src/main/java/com/blockguard/server/domain/news/scheduler/NewsSaveScheduler.java
Labels: ➕ Refactor, 🐼 채유
