Repository Block-Guard/BlockGuard-Server, pull requests merged in 2025-07, with the labels that each got.

#2 fix: exclude security configuration
  src/main/java/com/blockguard/server/ServerApplication.java
Labels: 🐼 채유

#5 [Feat] 회원가입/로그인 API
  build.gradle
  src/main/java/com/blockguard/server/domain/auth/api/AuthApi.java
  src/main/java/com/blockguard/server/domain/auth/application/AuthService.java
  src/main/java/com/blockguard/server/domain/auth/domain/JwtToken.java
  src/main/java/com/blockguard/server/domain/auth/dto/JwtDto.java
  src/main/java/com/blockguard/server/domain/auth/enhancer/JwtAuthenticationFilter.java
  src/main/java/com/blockguard/server/domain/auth/enums/JwtGrantType.java
  src/main/java/com/blockguard/server/domain/auth/enums/JwtTokenExpireTime.java
  src/main/java/com/blockguard/server/domain/auth/infra/JwtTokenGenerator.java
  src/main/java/com/blockguard/server/domain/auth/infra/JwtTokenProvider.java
  src/main/java/com/blockguard/server/domain/user/dao/UserRepository.java
  src/main/java/com/blockguard/server/domain/user/domain/User.java
  src/main/java/com/blockguard/server/domain/user/domain/enums/Gender.java
  src/main/java/com/blockguard/server/domain/user/dto/request/LoginRequest.java
  src/main/java/com/blockguard/server/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/blockguard/server/domain/user/dto/response/LoginResponse.java
  src/main/java/com/blockguard/server/domain/user/dto/response/RegisterResponse.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/global/config/SwaggerConfig.java
  src/main/java/com/blockguard/server/global/config/WebMvcConfig.java
Labels: 🐼 채유

#22 [Fix] 이미지 업로드 용량 초과 예외 처리 & 보호자 이름 유니크 제약 및 예외 처리
  src/main/java/com/blockguard/server/domain/guardian/application/GuardianService.java
  src/main/java/com/blockguard/server/domain/guardian/dao/GuardianRepository.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/com/blockguard/server/global/exception/GlobalExceptionHandler.java
Labels: 🐞 BugFix, 🐶 연주

#24 [Feat] 이메일 중복 확인 API
  src/main/java/com/blockguard/server/domain/auth/api/AuthApi.java
  src/main/java/com/blockguard/server/domain/auth/application/AuthService.java
  src/main/java/com/blockguard/server/domain/user/dto/request/CheckEmailDuplicatedRequest.java
  src/main/java/com/blockguard/server/domain/user/dto/response/CheckEmailDuplicatedResponse.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/com/blockguard/server/global/exception/GlobalExceptionHandler.java
Labels: 🐼 채유, 🚀 Feature

#27 [Feat] 사기 분석 API 및 OCR API 연동
  src/main/java/com/blockguard/server/domain/analysis/api/FraudAnalysisApi.java
  src/main/java/com/blockguard/server/domain/analysis/application/FraudAnalysisService.java
  src/main/java/com/blockguard/server/domain/analysis/dto/request/FraudAnalysisRequest.java
  src/main/java/com/blockguard/server/domain/analysis/dto/request/GptRequest.java
  src/main/java/com/blockguard/server/domain/analysis/dto/response/FraudAnalysisResponse.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/MultipartConfig.java
  src/main/java/com/blockguard/server/global/config/RestTemplateConfig.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/infra/ocr/ByteArrayResourceWithFilename.java
  src/main/java/com/blockguard/server/infra/ocr/NaverOcrClient.java
Labels: 🐼 채유, 🚀 Feature

#32 [Feat] URL 사기분석 API
  src/main/java/com/blockguard/server/domain/admin/api/AdminApi.java
  src/main/java/com/blockguard/server/domain/analysis/api/FraudAnalysisApi.java
  src/main/java/com/blockguard/server/domain/analysis/domain/enums/RiskLevel.java
  src/main/java/com/blockguard/server/domain/fraud/api/FraudApi.java
  src/main/java/com/blockguard/server/domain/fraud/application/FraudService.java
  src/main/java/com/blockguard/server/domain/fraud/dao/FraudUrlRepository.java
  src/main/java/com/blockguard/server/domain/fraud/domain/FraudUrl.java
  src/main/java/com/blockguard/server/domain/fraud/dto/request/FraudUrlRequest.java
  src/main/java/com/blockguard/server/domain/fraud/dto/response/FraudUrlResponse.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/SecurityConfig.java
  src/main/java/com/blockguard/server/infra/google/GoogleSafeBrowsingClient.java
  src/main/java/com/blockguard/server/infra/importer/FraudUrlImporter.java
Labels: 🐼 채유, 🚀 Feature

#39 [Refactor] 공공데이터 API 버전 변경
  src/main/java/com/blockguard/server/infra/importer/FraudUrlImporter.java
Labels: ➕ Refactor, 🐼 채유

#40 [Feat] 긴급대응 API
  src/main/java/com/blockguard/server/domain/report/api/ReportRecordApi.java
  src/main/java/com/blockguard/server/domain/report/application/ReportRecordService.java
  src/main/java/com/blockguard/server/domain/report/dao/UserReportRecordRepository.java
  src/main/java/com/blockguard/server/domain/report/domain/ReportStepCheckbox.java
  src/main/java/com/blockguard/server/domain/report/domain/ReportStepProgress.java
  src/main/java/com/blockguard/server/domain/report/domain/UserReportRecord.java
  src/main/java/com/blockguard/server/domain/report/domain/enums/CheckboxType.java
  src/main/java/com/blockguard/server/domain/report/domain/enums/ReportStep.java
  src/main/java/com/blockguard/server/domain/report/domain/enums/ReportStepCheckboxConfig.java
  src/main/java/com/blockguard/server/domain/report/dto/request/UpdateReportStepRequest.java
  src/main/java/com/blockguard/server/domain/report/dto/response/CurrentReportRecordResponse.java
  src/main/java/com/blockguard/server/domain/report/dto/response/ReportRecordResponse.java
  src/main/java/com/blockguard/server/domain/report/dto/response/ReportRecordStepResponse.java
  src/main/java/com/blockguard/server/global/common/codes/ErrorCode.java
  src/main/java/com/blockguard/server/global/common/codes/SuccessCode.java
  src/main/java/com/blockguard/server/global/config/swagger/SwaggerResponseDescription.java
Labels: 🐶 연주, 🚀 Feature

#43 [Refactor] AI 서버 통신 로직 리펙토링
  src/main/java/com/blockguard/server/domain/analysis/application/FraudAnalysisService.java
  src/main/java/com/blockguard/server/infra/gpt/GptApiClient.java
Labels: ➕ Refactor, 🐶 연주
